spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: "jdbc:postgresql://localhost:5432/sgms"
    username: "postgres"
    password: "postgres"
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: [ "health", "functions" ]