spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost:5432/sgms}"
    username: "postgres"
    password: "${DB_PASSWORD:postgres}"
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: [ "health", "functions" ]